title: Rețetar
description: Rețete fără aditivi pentru oameni organizați

github:
  repository:
    name: retetar
    url: https://github.com/mihnea-mihai/retetar
  user:
    name: mihnea-mihai
    url: https://github.com/mihnea-mihai/

collections:
  retete:
    output: true
  mese:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: retete
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: mese
    values:
      layout: "meal"
