title: Rețetar
description: Rețete fără aditivi pentru oameni organizați 

github:
  repository:
    name: retetar
    url: https://github.com/mihnea-mihai/retetar
  user:
    name: mihnea-mihai
    url: https://github.com/mihnea-mihai/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"